name: BuildImage
on:
  workflow_call:

jobs:
  build-image:
    name: BuildImage
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: BuildImage
        id: build
        run: |
          echo "This is a BuildImage stage"
