name: IntegrationTest
on:
  workflow_call:

jobs:
  integration-test:
    name: IntegrationTest
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: IntegrationTest
        id: build
        run: |
          echo "This is a IntegrationTest stage"
