name: Release
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        id: build
        run: |
          echo "This is a Release stage"
