name: StaticAnalysis
on:
  workflow_call:

jobs:
  static-analysis:
    name: StaticAnalysis
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: StaticAnalysis
        id: build
        run: |
          echo "This is a StaticAnalysis stage"
