name: SystemTest
on:
  workflow_call:

jobs:
  system-test:
    name: SystemTest
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SystemTest
        id: build
        run: |
          echo "This is a SystemTest stage"
