name: UnitTest
on:
  workflow_call:

jobs:
  unit-test:
    name: UnitTest
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: UnitTest
        id: build
        run: |
          echo "This is a UnitTest stage"
